web:
  build: .
  command: 'crystal run src/app.cr'
  working_dir: /app/user
  environment:
    PORT: 3000
    DATABASE_URL: 'postgres://postgres:@pg:5432/postgres'
  ports:
    - '80:3000'
  links:
    - pg
  volumes:
    - '.:/app/user'
spec:
  build: .
  command: 'crystal spec'
  working_dir: /app/user
  volumes:
    - '.:/app/user'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 3000
    DATABASE_URL: 'postgres://postgres:@pg:5432/postgres'
  ports:
    - '80:3000'
  links:
    - pg
  volumes:
    - '.:/app/user'
pg:
  image: postgres


